apiVersion: v1
kind: Service
metadata:
  name: icon-scout-service
spec:
  selector:
    app: icon-scout
  ports:
    - protocol: TCP
      port: 80 # The port the service will expose
      targetPort: 3000 # The port your container listens on
  type: LoadBalancer # Allows you to access the app from outside Minikube
