name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/gruberb/icon-scout:latest

      - name: Push the Docker image
        run: |
          docker push ghcr.io/gruberb/icon-scout:latest
